/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RosterIndexRouteImport } from './routes/roster/index'
import { Route as RosterNewRouteImport } from './routes/roster/new'
import { Route as RosterIdIndexRouteImport } from './routes/roster/$id/index'
import { Route as RosterIdEditRouteImport } from './routes/roster/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIndexRoute = RosterIndexRouteImport.update({
  id: '/roster/',
  path: '/roster/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterNewRoute = RosterNewRouteImport.update({
  id: '/roster/new',
  path: '/roster/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIdIndexRoute = RosterIdIndexRouteImport.update({
  id: '/roster/$id/',
  path: '/roster/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterIdEditRoute = RosterIdEditRouteImport.update({
  id: '/roster/$id/edit',
  path: '/roster/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/roster/new': typeof RosterNewRoute
  '/roster/': typeof RosterIndexRoute
  '/roster/$id/edit': typeof RosterIdEditRoute
  '/roster/$id/': typeof RosterIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/roster/new': typeof RosterNewRoute
  '/roster': typeof RosterIndexRoute
  '/roster/$id/edit': typeof RosterIdEditRoute
  '/roster/$id': typeof RosterIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/roster/new': typeof RosterNewRoute
  '/roster/': typeof RosterIndexRoute
  '/roster/$id/edit': typeof RosterIdEditRoute
  '/roster/$id/': typeof RosterIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/roster/new'
    | '/roster/'
    | '/roster/$id/edit'
    | '/roster/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/roster/new' | '/roster' | '/roster/$id/edit' | '/roster/$id'
  id:
    | '__root__'
    | '/'
    | '/roster/new'
    | '/roster/'
    | '/roster/$id/edit'
    | '/roster/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RosterNewRoute: typeof RosterNewRoute
  RosterIndexRoute: typeof RosterIndexRoute
  RosterIdEditRoute: typeof RosterIdEditRoute
  RosterIdIndexRoute: typeof RosterIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/': {
      id: '/roster/'
      path: '/roster'
      fullPath: '/roster/'
      preLoaderRoute: typeof RosterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/new': {
      id: '/roster/new'
      path: '/roster/new'
      fullPath: '/roster/new'
      preLoaderRoute: typeof RosterNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$id/': {
      id: '/roster/$id/'
      path: '/roster/$id'
      fullPath: '/roster/$id/'
      preLoaderRoute: typeof RosterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$id/edit': {
      id: '/roster/$id/edit'
      path: '/roster/$id/edit'
      fullPath: '/roster/$id/edit'
      preLoaderRoute: typeof RosterIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RosterNewRoute: RosterNewRoute,
  RosterIndexRoute: RosterIndexRoute,
  RosterIdEditRoute: RosterIdEditRoute,
  RosterIdIndexRoute: RosterIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
