name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-with-typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: latest
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
      - run: pnpm i --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v7
        with:
          node-version: latest
          cache: pnpm
          registry-url: 'https://npm.pkg.github.com'
      - run: pnpm i --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm test

  biome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: biomejs/setup-biome@v2
        with:
          version: latest
      - run: biome ci .
